apiVersion: v1
kind: Service
metadata:
  name: my-restful-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 31234
  selector:
    app: my-restful-service
